# Generated by Django 5.0.7 on 2024-07-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_event_allowed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='accessible',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
