# Generated by Django 5.0.7 on 2024-07-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_game_accessible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='accessible',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
