# Generated by Django 5.0.7 on 2024-07-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_game_accessible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='bgg_url',
        ),
    ]
