# Generated by Django 5.0.7 on 2024-07-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_renter_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='list_of_renters',
            field=models.ManyToManyField(blank=True, default=None, related_name='rented_games', to='core.renter'),
        ),
    ]
