# Generated by Django 5.0.7 on 2024-07-17 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_game_list_of_renters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='event',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
    ]
