# Generated by Django 5.0.7 on 2024-07-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_renter_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='has_rented',
            field=models.BooleanField(default=False),
        ),
    ]
