# Generated by Django 5.0.7 on 2024-07-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_renter_has_rented_renter_how_many_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
