# Generated by Django 5.0.7 on 2024-07-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_game_avg_rating_game_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
