# Generated by Django 5.0.7 on 2024-08-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='barcode',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
