# Generated by Django 5.0.7 on 2024-08-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_game_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='known_distributors',
            field=models.ManyToManyField(default=None, related_name='distributors', to='core.game'),
        ),
    ]
