# Generated by Django 5.0.7 on 2024-08-07 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_event_known_distributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='known_distributors',
        ),
        migrations.CreateModel(
            name='KnownDistributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor', models.CharField(max_length=100)),
                ('event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
        ),
    ]
