# Generated by Django 5.0.7 on 2024-08-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_event_known_distributors_knowndistributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='max_playtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='min_players',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='min_playtime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
