# Generated by Django 5.0.7 on 2024-08-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_game_max_players_game_max_playtime_game_min_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='mechanics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
