# Generated by Django 5.0.7 on 2024-08-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_game_categories_game_mechanics'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
