# Generated by Django 5.0.7 on 2024-08-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_game_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.AddField(
            model_name='game',
            name='complexity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
